[supervisord]
nodaemon=true
logfile=/dev/stdout
logfile_maxbytes=0
pidfile=/tmp/supervisord.pid
childlogdir=/tmp

[program:api]
command=uvicorn app.main:app --host 0.0.0.0 --port %(ENV_PORT)s --no-access-log
directory=/app
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
redirect_stderr=true

[program:worker]
command=celery -A app.workers.celery worker --loglevel=INFO --concurrency=1
directory=/app
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stopwaitsecs=30
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
redirect_stderr=true

[program:beat]
command=celery -A app.workers.celery beat --loglevel=INFO --schedule=/tmp/celerybeat-schedule
directory=/app
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
redirect_stderr=true